test_that("semaphores work", {
  expect_error(sem_open("/bmc_sem_test", create = FALSE))
  s <- sem_open("/bmc_sem_test", create = TRUE, value = 1)
  expect_type(s, "externalptr")
  s <- sem_open("/bmc_sem_test", create = TRUE, overwrite = TRUE)
  sem_wait(s)
  sem_post(s)
  sem_wait(s)
  sem_close(s)
  sem_close(s)
  expect_error(sem_close(s))
  sem_unlink("/bmc_sem_test")
  expect_error(sem_unlink("/bmc_sem_test"))
})
