test_that("semaphores work", {
  sem_name <- gen_posix_name()
  expect_error(sem_open(sem_name, create = FALSE))
  s <- sem_open(sem_name, create = TRUE, value = 1)
  expect_type(s, "externalptr")
  s <- sem_open(sem_name, create = TRUE, overwrite = TRUE)
  sem_wait(s)
  sem_post(s)
  sem_wait(s)
  sem_close(s)
  sem_unlink(sem_name)
  expect_error(sem_unlink(sem_name))
})
